### ISSUE TITLE
Server should include Unit ID in event parameters

### ISSUE THREAD

**Issue by johnsoftek** [dresende/node-modbus-tcp#10]
The events emitted by the server do not include the unit ID. This is a problem if the server supports multiple units.

**Comment by johnsoftek** [comment]
Okay. I discovered that the events also include the data object as the last parameter, so unitId is accessible as data.unitId.

It would still be nice if unitId were exposed as a separate parameter.

**Comment by dresende** [comment]
Please use [modbus-stream](https://github.com/dresende/node-modbus-stream) as I'm no longer maintaining this module.
