### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by kjetilmjos** [dresende/node-modbus-tcp#12]
I installed modbus-tcp and tried to run the example but I get this error:
![image](https://cloud.githubusercontent.com/assets/14892396/10169242/825ed044-66d0-11e5-80b7-517aeec8f5a3.png)

Any idea what I'm doing wrong?

**Comment by Laro88** [comment]
The stream object is undefined, stating the obvious :-)
Any chance that you can post your code. I have it running fine - got some performance problems, but it is most likely not in the modbus-tcp.
I can post some running code tomorrow morning CET.

**Comment by kjetilmjos** [comment]
Thanks for your reply! 

Just wanted to do a test using the example code so i installed the package using:
npm install modbus-tcp

And tried the example code:
var modbus = require("modbus-tcp");
var client = new modbus.Client();
var server = new modbus.Server();

// link client and server streams together
client.pipe(server.pipe());
server.pipe(client.pipe());

server.on("read-coils", function (from, to, reply) {
    return reply(null, [ 1, 0, 1, 1 ]);
});

// read coils from unit id = 0, from address 10 to 13
client.readCoils(0, 10, 13, function (err, coils) {
    // coils = [ 1, 0, 1, 1 ]
});

I'm totally new to node so probably missing some stupid newbie mistake.

**Comment by dresende** [comment]
Try changing the 2 `pipe()` lines to this:

```js
client.writer().pipe(server.reader());
server.writer().pipe(client.reader());
```

**Comment by dresende** [comment]
Open example, open developer tools to see console output and run the code.

http://requirebin.com/?gist=83f786b4f69b984b2ff5

**Comment by Laro88** [comment]
Snippets from running code:
```
var client = new modbustcp.Client();

//inside nt.createServer (physical modbus hw initiates socket and goes through authentication before switching its internal IO state to modbus on tcp
client.writer().pipe(socket);
socket.pipe(client.reader()); //socket is from net.createServer(function (socket) {....
```

**Comment by dresende** [comment]
I also use net sockets and that's why where the `.pipe()` from this modbus module works best. In your case you would just do:

```js
var client = new modbustcp.Client();

client.pipe(socket);
```

Internally `pipe()` will attach the read and write streams to that socket.
