### ISSUE TITLE
How to use an error on reply function

### ISSUE THREAD

**Issue by jkujanpa** [dresende/node-modbus-tcp#13]
Hey there,

Maybe not an issue, but I noticed that there are also some questions here.

I'm wondering how to use the error parameter on reply function on a server event. 
As far as I have understood, server should return exception code on error, e.g. if coil values are tried to read outside from the memory area.

I have following test code on my server side:

    modServer.on("read-coils", (from, to, reply) => {
        if (from > memory.coils.maxAddr) {
            return reply(ExceptionCodes.ILLEGAL_DATA_VALUE, null);
        }
        return reply(null, [ 1, 0, 1, 1 ]);
    });

And I'm expecting to get error code 3 (ExceptionCodes.ILLEGAL_DATA_VALUE) or similar on a client side, which is something like this

    modClient.readCoils(0, 3000, 100, function (err, coils) {
        if (err) {
            console.log('Client: Read Error: ' + err);
            return;
        }
        console.log('Client: coils read: ' + coils);
    });

However, I got "Client: Read Error: Error: 0", and I got an error only on first read.
Can anyone tell me what I am missing?

Thank you.

**Comment by dresende** [comment]
I don't know how this issue didn't get to my inbox. Thank you so much for pointing it, I'm fixing it ASAP.
