### ISSUE TITLE
Server read-holding-register() api failed

### ISSUE THREAD

**Issue by NNM11** [dresende/node-modbus-tcp#15]
I create a server to handle the API.   The 'read-holding-registers' API failed with an error that I am not  sure what is going on.   Also, is there example of all of these API?  Thanks

    // response to read-holding-registers
    server.on("read-holding-registers", function (from, to, reply) {
	console.log('read-holding-registers');
	// { fc: 3, byteCount: 20, register: [ values 0 - 10 ] }
	var regs = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ];
        return reply(null, regs );
    });

The server failed when it responds to a client call 

      client.readholdingregister(0, 0, 10, f(err, resp) {
           console.log(resp);
      });

---
server listens @127.0.0.1:8888
read-coils
read-holding-registers
/archive-modbus/node_modules/modbus-tcp/lib/protocol/READ_HOLDING_REGISTERS.js:18
		registers[i].copy(buf, (i * 2) + 1, 0, 2);
		             ^

TypeError: registers[i].copy is not a function
    at Object.exports.response [as readHoldingRegistersResponse] (archive-modbus/node_modules/modbus-tcp/lib/protocol/READ_HOLDING_REGISTERS.js:18:16)

**Comment by dresende** [comment]
Try updating to latest version. If the problem persists, please reopen.

**Comment by Clocker** [comment]
Hello,
I started yesterday with your project. I run into the same errors like NNM11.
Everything I do with registers end in the error.

`TypeError: registers[i].copy is not a function`

I think I'am misssing something, but I do not know what?
Or I'am using the mobus tcp function for register not in the right way.
May be you can give me an example for that.

I called it like

`server.on("write-single-register", function (addr, val, reply) {
	console.log('Server was written', val)
    return reply(null, val);
});

// write register from unit id = 0, at address 1 with value 134
client.writeSingleRegister(0, 1, 134, function (err, reg) {
    	console.log('Response from Server ', reg);
});`

Thank you for your help

**Comment by dresende** [comment]
Since records always have 2 bytes, it's safer and sometimes (like this) it's mandatory to use an `Array` of `Buffer`. The example @NNM11 gave should be more like this:

```js
// response to read-holding-registers
server.on("read-holding-registers", function (from, to, reply) {
console.log('read-holding-registers');
// { fc: 3, byteCount: 20, register: [ values 0 - 10 ] }
var regs = [ new Buffer([ 1, 2 ]), new Buffer([ 3, 4 ]), new Buffer([ 5, 6 ]), new Buffer([ 7, 8 ]), new Buffer([ 9, 10 ]) ];
    return reply(null, regs );
});
```

**Comment by Pavan-rmes** [comment]
//if the values are greater than 256 its not working

// this function takes the input and gives the output in the array format

function convertValues(num){
    let firstPart = Math.floor(num/256)
    let lastPart = num%256
    return (new Buffer.from([firstPart,lastPart]))
}
// for 5 registers
var reg =var regs = [ convertValues(257),convertValues(258),convertValues(259),convertValues(260),convetValues(2547) ];

// this works for me
