### ISSUE TITLE
TCP connection

### ISSUE THREAD

**Issue by rcorveira** [dresende/node-modbus-tcp#16]
Hello, 
Where do i define the TCP address of the device i need to access?
Exemple: Connect to a master server and read the registers from Slave ID (Slave:192.168.102.7 and ID: 4)
Best regards
RC

**Comment by saynono** [comment]
Have a look here:
https://github.com/dresende/node-modbus-tcp/issues/5

**Comment by hansnn** [comment]
Thank you very much

**Comment by rcorveira** [comment]
ok, thanks, i will try and see if i can connect.
Best Regards
