### ISSUE TITLE
Server write-single-register() api failed (Reopened)

### ISSUE THREAD

**Issue by Clocker** [dresende/node-modbus-tcp#18]
Hello,
I started yesterday with your project. I run into the same errors like NNM11. (see issue https://github.com/dresende/node-modbus-tcp/issues/15)

Everything I do with registers end in the error.

`TypeError: registers[i].copy is not a function`

I think I'am misssing something, but I do not know what?
Or I'am using the mobus tcp function for register not in the right way.
May be you can give me an example for that.

I called it like

```js
server.on("write-single-register", function (addr, val, reply) {
	console.log('Server was written', val)
    return reply(null, val);
});

// write register from unit id = 0, at address 1 with value 134
client.writeSingleRegister(0, 1, 134, function (err, reg) {
    	console.log('Response from Server ', reg);
});
```

Thank you for your help

**Comment by dresende** [comment]
Try using the same technique. Send `new Buffer([ 0x0, 0x86 ])` instead of `134`.

https://github.com/dresende/node-modbus-tcp/issues/15#issuecomment-253265820
