### ISSUE TITLE
[Q] Is there a way to reset / unpipe?

### ISSUE THREAD

**Issue by jacobq** [dresende/node-modbus-tcp#23]
In my application I'd like to be able to disconnect / reconnect the underlying TCP connection w/o having to destroy and recreate the modbus client object. Is it safe to just call `client.pipe(newSocket)` (after already doing this with another connection/socket object) or will the object still have some references to the old one?

**Comment by dresende** [comment]
Yes, it should be if there's nothing pending around. Still, I wouldn't recommend.

**Comment by jacobq** [comment]
OK, that's good enough for me for now. Thanks.
