### ISSUE TITLE
writeMultipleRegisters  & readHoldingRegisters is not working after 6 to 7 days after service started

### ISSUE THREAD

**Issue by vishalb747** [dresende/node-modbus-tcp#26]
Please find the logs
[service.txt](https://github.com/dresende/node-modbus-tcp/files/1313135/service.txt)

Hello Sir,
         I have written node service to read the data from Modbus-tcp( from PLC) and write the data to modbuc-tcp. It works fine for 5 to 6 days but after that it does not work. I need to restart my service then it works properly. 
It is working properly for only read operation without any issue. I think writeMultipleRegisters is not free some instances

**Comment by Nedgeva** [comment]
If Modbus TCP server on you PLC closes connection after each request you can't simply reuse existing socket connection, so you need to destroy tcp socket instance *and* all currently piped event emitters (e.g. modbus tcp client) before opening new connection.
You can simply load test your script, running it's every tens of milliseconds and see what happening.

Please note: this package not maintained anymore.

**Comment by dresende** [comment]
Look at [modbus-stream](https://github.com/node-modbus/stream)
