### ISSUE TITLE
Modbus Slave example

### ISSUE THREAD

**Issue by kotopuz** [dresende/node-modbus-tcp#28]
I am struggle to make it work. I want to make a sinlge js file which will act as Modbus Slave (server).
I an new in node.js and after trying many npm-s somehow I can't make it work.Please help.

Can you please make an example with setInterval (just to run periodically or inside a infinite loop )  which will:
1. have server IP  , port and ID setup function.
2. Separate functions to read single holding reg, holding input, input coil and input reg.
3. Separate functions to write single holding reg, holding input, input coil and input reg.
4. Separate functions to read **multiple** holding reg, holding input, input coil and input reg.
5. Separate functions to write **multiple** holding reg, holding input, input coil and input reg.
6. Each function to consol.log VALUE, not object to clearly see what's going on. May be use return in each function for easier 

Not sure if it's only me, but in industial world Server and client mean nothing as Modbus has Master and Slave. Master is MAIN system collecting info and controlling Slaves.  I don't know why in all NPMs Master is actually client and Slave is actually server - sounds like all is apposite to common sense.

Structure might be:
// code to init vars and declare dependencies
....
// options [{}] .. settings of Modbus Slave

//declaration off functions written above 1-6
function 1(){}
..
function 6(){}
setInterval(function 1(), time)
...
setInterval(function 6(), time)
...
show to use return values
var inputcoil1=funct1()

Many thanks for your time and developing such a great NPM.

**Comment by dresende** [comment]
Hi. Take a look at #12
