### ISSUE TITLE
IP, PORT - how to configure?

### ISSUE THREAD

**Issue by mjoszko** [dresende/node-modbus-tcp#5]

**Comment by geon** [comment]
You don't. Just pipe the modbus client/server to a tcp socket you have already set up on the right IP and port.

My code looks something like this:

	console.log('connecting...');
	var socket = net.connect({
		host: host,
		port: 502
	}, function () {

		console.log('connected');
	});
	socket.on('error', function (error) {

		console.log('connection failed:', error.stack);
	});

	var modbusClient = new modbus.Client();
	modbusClient.writer().pipe(socket);
	socket.pipe(modbusClient.reader());

**Comment by sandeepbs39** [comment]
can you please share that full code..

**Comment by sandeepbs39** [comment]
how to configure?

**Comment by geon** [comment]
That *is* the full code to set it up. The variable `host` should obviously be the host of your modbus/tcp server.

**Comment by johnsoftek** [comment]
@geon Thanks for effort in setting this up.

I agree with @sandeepbs39. It would be really helpful to have the example above in the readme for streams noobs.

**Comment by sandeepbs39** [comment]
how to read multiple register

**Comment by sandeepbs39** [comment]
how to configure the code for free register

**Comment by annaaaaaaaaaaaaaaaaaaaa** [comment]
that code works only for read the register can you please share how to write in to the register..

**Comment by dresende** [comment]
This is not an issue. You need to know more about the protocol and device modbus tables. Yes, it sucks, I know.
